<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\Shipping\Block\Adminhtml\View\Form $block
 */
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
$order = $block->getShipment()->getOrder();
?>
<?= $block->getChildHtml('order_info'); ?>
<section class="admin__page-section order-shipment-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Payment &amp; Shipping Method')); ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Payment Information')); ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div><?= $block->getChildHtml('order_payment') ?></div>
                <div class="order-payment-currency">
                    <?= $block->escapeHtml(__('The order was placed using %1.', $order->getOrderCurrencyCode())); ?>
                </div>
            </div>
        </div>

        <div class="admin__page-section-item order-shipping-address">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Shipping and Tracking Information')); ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="shipping-description-wrapper">
                    <?php if ($block->getShipment()->getTracksCollection()->count()) : ?>
                        <p>
                            <a href="#" id="linkId"
                               onclick="popWin('<?= $block->escapeHtmlAttr($block->escapeUrl($this->helper(\Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($block->getShipment()))); ?>','trackshipment','width=800,height=600,resizable=yes,scrollbars=yes')"
                               title="<?= $block->escapeHtmlAttr(__('Track this shipment')); ?>">
                                <?= $block->escapeHtml(__('Track this shipment')); ?>
                            </a>
                        </p>
                    <?php endif; ?>
                    <div class="shipping-description-title">
                        <?= $block->escapeHtml($order->getShippingDescription()); ?>
                    </div>

                    <?= $block->escapeHtml(__('Total Shipping Charges')); ?>:

                    <?php if ($this->helper(\Magento\Tax\Helper\Data::class)->displayShippingPriceIncludingTax()) : ?>
                        <?php $excl = $block->displayShippingPriceInclTax($order); ?>
                    <?php else : ?>
                        <?php $excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                    <?php endif; ?>
                    <?php $incl = $block->displayShippingPriceInclTax($order); ?>

                    <?= /* @noEscape */
                    $excl; ?>
                    <?php if ($this->helper(\Magento\Tax\Helper\Data::class)->displayShippingBothPrices() && $incl != $excl) : ?>
                        (<?= $block->escapeHtml(__('Incl. Tax')); ?> <?= /* @noEscape */
                        $incl; ?>)
                    <?php endif; ?>
                </div>

                <p>
                    <?php if ($block->canCreateShippingLabel()) : ?>
                        <?= /* @noEscape */
                        $block->getCreateLabelButton(); ?>
                    <?php endif ?>
                    <?php if ($block->getShipment()->getShippingLabel()) : ?>
                        <?= /* @noEscape */
                        $block->getPrintLabelButton(); ?>
                    <?php endif ?>
                    <?php if ($block->getShipment()->getPackages()) : ?>
                        <?= /* @noEscape */
                        $block->getShowPackagesButton(); ?>
                    <?php endif ?>
                </p>
                <?= $block->getChildHtml('shipment_tracking'); ?>

                <?= $block->getChildHtml('shipment_packaging'); ?>
                <script>
                    require([
                        'jquery',
                        'prototype'
                    ], function (jQuery) {
                        var setCallbacks = function () {
                            window.packaging.setConfirmPackagingCallback(function () {
                                window.packaging.sendCreateLabelRequest();
                            });
                            window.packaging.setLabelCreatedCallback(function () {
                                setLocation("<?= $block->escapeUrl($block->getUrl('adminhtml/order_shipment/view', ['shipment_id' => $block->getShipment()->getId()])); ?>");
                            });
                        };

                        if (jQuery(document).data('packagingInited')) {
                            setCallbacks();
                        } else {
                            jQuery(document).on('packaging:inited', setCallbacks);
                        }
                    });
                </script>
            </div>
        </div>
    </div>
</section>
<div><?= $block->getChildHtml('extra_shipment_info') ?></div>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Items Shipped')); ?></span>
    </div>
    <?= $block->getChildHtml('shipment_items'); ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order Total')); ?></span>
    </div>
    <div class="admin__page-section-content">
        <?= $block->getChildHtml('shipment_packed'); ?>

        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Shipment History')); ?></span>
            </div>
            <div class="admin__page-section-item-content"><?= $block->getChildHtml('order_comments'); ?></div>
        </div>
        <!--test-->

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Order Totals') ?></span>
            </div>
            <table class="data-table admin__table-secondary order-subtotal-table">

                <tfoot>
                <tr class="col-0">
                    <td class="label">
                        <strong><?php echo __('Grand Total'); ?></strong>
                    </td>
                    <td>
                        <?php echo $block->displayPriceAttribute('grand_total', true, ''); ?>
                    </td>
                </tr>
                <tr class="col-1">
                    <td class="label">
                        <strong><?php echo __('Total Paid'); ?></strong>
                    </td>
                    <td>
                        <?php echo $block->displayPriceAttribute('total_paid', true, ''); ?>
                    </td>
                </tr>
                <tr class="col-2">
                    <td class="label">
                        <strong><?php echo __('Total Refunded') ?></strong>
                    </td>
                    <td>
                        <?php echo $block->displayPriceAttribute('total_refunded', true, ''); ?>
                    </td>
                </tr>
                <tr class="col-3">
                    <td class="label">
                        <strong><?php echo __('Total Due'); ?></strong>
                    </td>
                    <td>
                        <?php echo $block->displayPriceAttribute('total_due', true, ''); ?>
                    </td>
                </tr>
                </tfoot>

                <tbody>
                <tr class="col-0">
                    <td class="label">
                        <?php echo __('Subtotal'); ?>
                    </td>

                    <td>
                        <?php echo $block->displayPriceAttribute('subtotal', true, ''); ?>
                    </td>
                </tr>
                <?php if ($order->getDiscountAmount() != 0): ?>
                    <tr class="col-1">
                        <td class="label">
                            <?php echo 'Discount ( ' . $order->getDiscountDescription() . ' )'; ?>
                        </td>

                        <td>
                            <?php echo $block->displayPriceAttribute('discount_amount', true, ''); ?>
                        </td>
                    </tr>
                <?php endif; ?>

                <tr class="col-2">
                    <td class="label">
                        <?php echo __('Shipping &amp; Handling'); ?>
                    </td>

                    <td>
                        <?php echo $block->displayPriceAttribute('shipping_amount', true, ''); ?>
                    </td>
                </tr>
                <?php if ($order->getFee() > 0): ?>
                    <tr class="col-3">
                        <td class="label">
                            <?php echo __('Small order handling'); ?>
                        </td>

                        <td>
                            <?php echo $block->displayPriceAttribute('fee', true, ''); ?>
                        </td>
                    </tr>
                <?php endif; ?>

                <?php if ($order->getCustomdiscount() != 0): ?>
                    <tr class="col-4">
                        <td class="label">
                            <?php echo __('Green Discount'); ?>
                        </td>
                        <td>
                            <?php echo "-" . $block->displayPriceAttribute('customdiscount', true, ''); ?>
                        </td>
                    </tr>
                <?php endif; ?>

                <tr class="col-5">
                    <td class="label">
                        <?php echo __('Total Weight'); ?>
                    </td>
                    <td>
                        <span><?php echo $order->getWeight(); ?></span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <!--test-->
    </div>
</section>
